CREATE TABLE ups_devices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    server_room_id BIGINT UNSIGNED NOT NULL,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(160) NOT NULL,
    manufacturer VARCHAR(120) NULL,
    model VARCHAR(120) NULL,
    serial_number VARCHAR(120) NULL,
    rated_power_va INT UNSIGNED NULL,
    rated_power_w INT UNSIGNED NULL,
    ip_address VARCHAR(45) NULL,
    management_url VARCHAR(2048) NULL,
    battery_replaced_at DATE NULL,
    battery_replacement_interval_months SMALLINT UNSIGNED NOT NULL DEFAULT 36,
    operational_status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    notes TEXT NULL,
    archived_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_ups_devices_server_room FOREIGN KEY (server_room_id) REFERENCES server_rooms (id),
    CONSTRAINT chk_ups_devices_status CHECK (operational_status IN ('ACTIVE', 'MAINTENANCE', 'ALARM', 'RETIRED')),
    CONSTRAINT chk_ups_devices_power_va CHECK (rated_power_va IS NULL OR rated_power_va BETWEEN 1 AND 10000000),
    CONSTRAINT chk_ups_devices_power_w CHECK (rated_power_w IS NULL OR rated_power_w BETWEEN 1 AND 10000000),
    CONSTRAINT chk_ups_devices_battery_interval CHECK (battery_replacement_interval_months BETWEEN 1 AND 240),
    UNIQUE KEY uq_ups_devices_code (code),
    INDEX idx_ups_devices_server_room (server_room_id),
    INDEX idx_ups_devices_status (operational_status),
    INDEX idx_ups_devices_archived (archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
