CREATE TABLE workspace_settings (
    id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,
    tier VARCHAR(160) NULL,
    region VARCHAR(160) NULL,
    network_map_subtitle VARCHAR(255) NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO workspace_settings (id) VALUES (1);
